% Nonlinear torque allocation for a satellite with rotatable appendages
% (aerodynamic torque generated by the VLEO Aerodynamics Tool, VAT).
%
% Finds the two fin deflections that bring the aerodynamic torque as close
% as possible to a commanded tau_des.
%
% On the solver
% -------------
% The objective is a 2-variable least-squares fit of a 3-vector residual,
% evaluated by an expensive but perfectly deterministic simulation. Three
% properties of it drive the method used below:
%
%  1. It is a SUM OF SQUARES, so Gauss-Newton applies: the Jacobian of the
%     3x1 residual gives a curvature model for free. A generic scalar
%     minimiser throws that structure away.
%  2. It is PIECEWISE smooth. eta enters as max(eta,0) for one panel of a
%     pair and max(-eta,0) for the other, so at eta = 0 the panel that
%     deploys swaps and the derivative jumps. The box therefore splits into
%     four quadrants, each of which IS smooth, and each is solved separately.
%     Starting at eta = [0;0] sits exactly on that crease and misleads any
%     gradient estimate.
%  3. Visibility is binary per triangle, so the torque carries a small
%     staircase, and the default sqrt(eps) finite-difference step would
%     differentiate pure quantisation noise. FD_STEP below is ~0.6 deg.
%     The exact value turns out not to matter much: measured over 0.06 to
%     3.4 deg the recovered eta moves by only 0.01 to 0.05 deg with no
%     failures, because the seeding stage already lands in the right basin
%     and the final accuracy is set by the shading quantisation rather
%     than by Jacobian quality. 0.6 deg was simply the fastest of those.
%
% Speed comes from doing the searching on a cheap mesh and only the final
% polish on the production mesh, which costs ~27 production evaluations.
%
% Requires base MATLAB only. patternsearch/fmincon/lsqnonlin live in the
% Optimization and Global Optimization Toolboxes, which are not needed here.
%
% Prerequisites, from the repository root:
%   pixi run build-matlab
%   addpath('matlab'); addpath('matlab\bin')

vat.setLogLevel("warn");   % minimal logging

%% ---- Flow / attitude parameters ----
alpha__rad  = deg2rad(40);  % angle of attack
beta__rad   = deg2rad(20);  % sideslip angle
num_pixel   = 3000;        % shading resolution
eta_max     = deg2rad(90); % maximum allowed panel angles

%% ---- Aerodynamic model ----
T_env__K        = 934;      % atmospheric temperature
rho__kg_per_m3  = 1e-9;     % atmospheric density
ao_mass__kg     = 16 * 1.6605390689252e-27;  % atomic oxygen mass
alpha_e         = 0.95;     % energy accommodation coefficient
surface_temp__K = 300;      % spacecraft surface temperature

aero.conditions = vat.AeroConditions(rho__kg_per_m3, T_env__K, ao_mass__kg);
aero.model      = vat.gsi_models.Sentman(1, alpha_e);

%% ---- Geometry ----
fp.current_folder = fileparts(mfilename('fullpath'));
fp.obj_file       = fullfile(fp.current_folder, ...
    "geometries/shuttlecock_15360.obj");

% Coarse stand-in used only to decide WHERE the optimum is. Every
% shuttlecock_*.obj shares the same five objects and the same bounding box,
% so the hinge table below applies unchanged, and it evaluates ~5x faster.
fp.seed_obj_file  = fullfile(fp.current_folder, ...
    "geometries/shuttlecock_960.obj");

geometry      = vat.geometry.RotatableMeshGeometry(fp.obj_file);
seed_geometry = vat.geometry.RotatableMeshGeometry(fp.seed_obj_file);

% Uncomment once to confirm which mesh_id belongs to which panel — VAT
% mesh IDs are 0-based (assimp load order), so the numbering below is
% only correct if the shuttlecock body itself occupies mesh 0.
% vat.visualization.show_meshes(geometry);

% Rotatable fins: mesh_id, hinge origin, hinge axis.
wings.up     = struct('mesh_id', 4, 'origin', [-0.15 -0.10 -0.05], ...
    'axis', [0 -1  0]);
wings.bottom = struct('mesh_id', 1, 'origin', [-0.15  0.10  0.05], ...
    'axis', [0  1  0]);
wings.left   = struct('mesh_id', 2, 'origin', [-0.15 -0.05  0.10], ...
    'axis', [0  0  1]);
wings.right  = struct('mesh_id', 3, 'origin', [-0.15  0.05 -0.10], ...
    'axis', [0  0 -1]);

%% ---- Shading / load pipelines ----
% Algorithm 0 = Binary. Do not switch to CoP (1) here: it reports occluded
% triangles as exposed, see matlab/bug_cop_shading.m.
pipeline   = vat.shading.ShadingPipeline(geometry, 0, num_pixel);
calculator = vat.loads.HybridForceTorqueCalculator( ...
    geometry, pipeline, aero.model);

seed_pipeline   = vat.shading.ShadingPipeline(seed_geometry, 0, 1000);
seed_calculator = vat.loads.HybridForceTorqueCalculator( ...
    seed_geometry, seed_pipeline, aero.model);

%% ---- Relative flow vector ----
% Standard wind-axes convention with alpha and beta
v_rel_fun = @(a, b, v) v .* [cos(a)*cos(b), sin(b), sin(a)*cos(b)];
v_rel__m_per_s = v_rel_fun(alpha__rad, beta__rad, 7800);

%% ---- Torque function handles ----
% eta1: up/bottom fins, eta2: left/right fins
torque_fun = @(eta) compute_torque(v_rel__m_per_s, geometry, ...
    aero.conditions, calculator, wings, surface_temp__K, eta(1), eta(2));

seed_torque_fun = @(eta) compute_torque(v_rel__m_per_s, seed_geometry, ...
    aero.conditions, seed_calculator, wings, surface_temp__K, eta(1), eta(2));

%% ---- Allocation ----
tau_des = [0; 0; 0];        % commanded torque [Nm]

% Residuals are expressed in micro-Nm. Torques here are ~1e-5 Nm, so the
% raw sum of squares is ~1e-10 and every default tolerance in MATLAB would
% be met instantly, long before the solver has actually converged.
TORQUE_SCALE = 1e6;
FD_STEP      = 1e-2;        % finite-difference step [rad], ~0.57 deg

residual      = @(eta) (torque_fun(eta)      - tau_des) * TORQUE_SCALE;
seed_residual = @(eta) (seed_torque_fun(eta) - tau_des) * TORQUE_SCALE;

t_start = tic;
[eta_opt, alloc] = allocate(residual, seed_residual, eta_max, FD_STEP);
t_alloc = toc(t_start);

%% ---- Report ----
tau_achieved = torque_fun(eta_opt);
tau_stowed   = torque_fun([0; 0]);

fprintf('\nAllocation finished in %.2f s\n', t_alloc);
fprintf('  production-mesh evaluations : %d\n', alloc.n_fine);
fprintf('  coarse-mesh evaluations     : %d\n', alloc.n_seed);
fprintf('  winning quadrant            : eta1 %s 0, eta2 %s 0  (exit: %s)\n', ...
    sign_label(eta_opt(1)), sign_label(eta_opt(2)), alloc.exit);
fprintf('\n  eta         = [%+8.3f %+8.3f] deg\n', rad2deg(eta_opt));
fprintf('  tau_des     = [%+11.4e %+11.4e %+11.4e] Nm\n', tau_des);
fprintf('  tau_achieved= [%+11.4e %+11.4e %+11.4e] Nm\n', tau_achieved);
fprintf('  residual    = %.4e Nm\n', norm(tau_achieved - tau_des));
fprintf('  (stowed |tau - tau_des| for comparison = %.4e Nm, improved %.1fx)\n', ...
    norm(tau_stowed - tau_des), ...
    norm(tau_stowed - tau_des) / max(norm(tau_achieved - tau_des), eps));

% Sanity check: no neighbour within one FD step may be better. If one is,
% the solve stopped early rather than at a genuine local minimum.
better = 0;
for d1 = [-FD_STEP 0 FD_STEP]
    for d2 = [-FD_STEP 0 FD_STEP]
        e = min(max(eta_opt + [d1; d2], -eta_max), eta_max);
        if norm(torque_fun(e) - tau_des) < norm(tau_achieved - tau_des) * (1 - 1e-9)
            better = better + 1;
        end
    end
end
fprintf('  neighbours within one FD step that beat it: %d (want 0)\n', better);

% Show the allocated configuration. The viewer blocks until closed, so it is
% skipped in a non-interactive session such as "matlab -batch".
set_panels(geometry, wings, eta_opt(1), eta_opt(2));
if usejava('desktop')
    vat.visualization.show_meshes(geometry);
    triangle_visibility = pipeline.shade(v_rel__m_per_s);
    vat.visualization.show_shading(geometry, triangle_visibility, ...
        v_rel__m_per_s);
end

%% ================= Allocation =================
function [x, info] = allocate(residual, seed_residual, eta_max, fd_step)
% Two-stage allocation.
%   stage 1  on the coarse mesh: grid-seed and solve each of the four
%            quadrants, to decide which one holds the optimum
%   stage 2  on the production mesh: polish only the winning quadrant
% Splitting by quadrant keeps every subproblem on one smooth branch of the
% max(eta,0) panel mapping.
    n_seed_grid = 4;
    info.n_fine = 0; info.n_seed = 0;
    count_seed = @(e) tick(seed_residual, e, 'seed');
    count_fine = @(e) tick(residual, e, 'fine');
    tick([], [], 'reset');

    quadrant_f = inf(1,4);
    quadrant_x = zeros(2,4);
    boxes_lb   = zeros(2,4);
    boxes_ub   = zeros(2,4);

    q = 0;
    for q1 = [1 -1]
        for q2 = [1 -1]
            q = q + 1;
            lb = [min(0, q1*eta_max); min(0, q2*eta_max)];
            ub = [max(0, q1*eta_max); max(0, q2*eta_max)];
            boxes_lb(:,q) = lb; boxes_ub(:,q) = ub;

            % Grid seed, skipping the crease at eta = 0.
            s1 = linspace(lb(1), ub(1), n_seed_grid+1); s1 = s1(2:end);
            s2 = linspace(lb(2), ub(2), n_seed_grid+1); s2 = s2(2:end);
            best_f = inf; seed = [s1(1); s2(1)];
            for i = 1:n_seed_grid
                for j = 1:n_seed_grid
                    f = sum(count_seed([s1(i); s2(j)]).^2);
                    if f < best_f, best_f = f; seed = [s1(i); s2(j)]; end
                end
            end

            % Cheap local solve, loose tolerance: this only has to pick the
            % right quadrant and a good starting point.
            quadrant_x(:,q) = lm_solve(count_seed, seed, lb, ub, ...
                fd_step = fd_step, max_iter = 25, tol_step = 1e-4);
            quadrant_f(q)   = sum(count_seed(quadrant_x(:,q)).^2);
        end
    end

    [~, winner] = min(quadrant_f);
    [x, lm_info] = lm_solve(count_fine, quadrant_x(:,winner), ...
        boxes_lb(:,winner), boxes_ub(:,winner), fd_step = fd_step, max_iter = 40);

    n = tick([], [], 'report');
    info.n_seed = n(1); info.n_fine = n(2);
    info.exit = lm_info.exit;
    info.quadrant_f = quadrant_f;
end

function out = tick(fn, e, mode)
% Evaluation counter shared by both stages.
    persistent n_seed n_fine
    if isempty(n_seed), n_seed = 0; n_fine = 0; end
    switch mode
        case 'reset',  n_seed = 0; n_fine = 0; out = [];
        case 'report', out = [n_seed n_fine];
        case 'seed',   n_seed = n_seed + 1; out = fn(e);
        case 'fine',   n_fine = n_fine + 1; out = fn(e);
    end
end

function [x, info] = lm_solve(residual, x0, lb, ub, opt)
%LM_SOLVE Bound-constrained Levenberg-Marquardt least squares, base MATLAB.
% Suits a small, expensive, piecewise-smooth residual: it needs only the
% residual vector, builds the Jacobian by finite differences, and damps the
% Gauss-Newton step until it actually reduces the residual.
    arguments
        residual function_handle
        x0 (:,1) double
        lb (:,1) double
        ub (:,1) double
        opt.fd_step  (1,1) double  = 1e-2
        opt.tol_step (1,1) double  = 1e-5
        opt.tol_grad (1,1) double  = 1e-10
        opt.max_iter (1,1) double  = 40
        opt.lambda0  (1,1) double  = 1e-3
    end
    n   = numel(x0);
    x   = min(max(x0, lb), ub);
    r   = residual(x); f = r.'*r;
    lam = opt.lambda0;
    info = struct('iterations', 0, 'exit', "max_iter", 'f', f);

    for it = 1:opt.max_iter
        % Central differences, with both probes kept inside the box. A
        % variable pinned to a bound is probed on whichever side has room;
        % differencing against a zero-width step would give a NaN Jacobian.
        J = zeros(numel(r), n);
        for k = 1:n
            hi = min(x(k) + opt.fd_step, ub(k));
            lo = max(x(k) - opt.fd_step, lb(k));
            if (hi - lo) > 0
                xp = x; xp(k) = hi;
                xm = x; xm(k) = lo;
                J(:,k) = (residual(xp) - residual(xm)) / (hi - lo);
            end
        end
        if ~all(isfinite(J(:))), info.exit = "bad_jacobian"; break, end

        grad = J.'*r;
        if norm(grad, inf) < opt.tol_grad, info.exit = "gradient"; break, end

        A       = J.'*J;
        scale   = max(diag(A), max(diag(A))*1e-6 + realmin);
        stepped = false;
        for inner = 1:30
            [dx, ok] = damped_step(A + lam*diag(scale), -grad);
            if ~ok, lam = min(lam*4, 1e10); continue, end
            xn = min(max(x + dx, lb), ub);
            rn = residual(xn); fn = rn.'*rn;
            if fn < f
                moved = norm(xn - x, inf);
                x = xn; r = rn; f = fn;
                lam = max(lam/3, 1e-10);
                stepped = true;
                if moved < opt.tol_step, info.exit = "step"; end
                break
            end
            lam = min(lam*4, 1e10);
        end
        info.iterations = it;
        if ~stepped
            % No downhill step at any damping: the residual is flat to
            % within the shading quantisation, which is as converged as it
            % can get on this mesh.
            info.exit = "stalled"; break
        end
        if info.exit == "step", break, end
    end
    info.f = f;
end

function [dx, ok] = damped_step(A, b)
    ok = true;
    w1 = warning('off', 'MATLAB:singularMatrix');
    w2 = warning('off', 'MATLAB:nearlySingularMatrix');
    dx = A \ b;
    warning(w1); warning(w2);
    if ~all(isfinite(dx)), dx = zeros(size(b)); ok = false; end
end

%% ================= Helper functions =================
function torque__Nm = compute_torque(v_rel__m_per_s, geometry, ...
    aero_conditions, calculator, wings, surface_temp__K, eta1, eta2)
% Rotate the fins to the commanded deflections, then evaluate the
% resulting aerodynamic torque about the flow direction v_rel__m_per_s.
% calc_aero_load returns [force, torque] (force first) — only the
% second output is the torque.

    set_panels(geometry, wings, eta1, eta2);
    [~, torque__Nm] = calculator.calc_aero_load( ...
        v_rel__m_per_s, surface_temp__K, aero_conditions);
    torque__Nm = torque__Nm(:);  % column vector, convenient for optimizers
end

function set_panels(geometry, wings, eta1__rad, eta2__rad)
% A positive eta deflects one panel of a pair, a negative eta its
% opposite. turn_mesh_around_axis is absolute, so every panel is
% commanded on every call and no state carries over between samples.
    turn(geometry, wings.up,     max( eta1__rad, 0));
    turn(geometry, wings.bottom, max(-eta1__rad, 0));
    turn(geometry, wings.left,   max( eta2__rad, 0));
    turn(geometry, wings.right,  max(-eta2__rad, 0));
end

function turn(geometry, wing, angle__rad)
    geometry.turn_mesh_around_axis( ...
        wing.mesh_id, angle__rad, wing.origin, wing.axis);
end

function s = sign_label(x)
    if x >= 0, s = '>='; else, s = '<='; end
end
