% Nonlinear torque allocation for a satellite with rotatable appendages
% (aerodynamic torque generated by the VLEO Aerodynamics Tool, VAT).
%
% Produces TORQUE_FUN, a function handle giving the aerodynamic torque
% as a function of two fin-deflection angles, for use inside an
% allocation / optimization routine (e.g. fmincon).

vat.setLogLevel("warn");   % minimal logging

%% ---- Flow / attitude parameters ----
alpha__rad  = deg2rad(4);  % angle of attack
beta__rad   = deg2rad(2);  % sideslip angle
num_pixel   = 3000;         % shading resolution
eta_max     = deg2rad(90);  % maximum allowed panel angles

%% ---- Aerodynamic model ----
T_env__K        = 934;      % atmospheric temperature
rho__kg_per_m3  = 1e-9;     % atmospheric density
ao_mass__kg     = 16 * 1.6605390689252e-27;  % atomic oxygen mass
alpha_e         = 0.95;     % energy accommodation coefficient
surface_temp__K = 300;      % spacecraft surface temperature

aero.conditions = vat.AeroConditions(rho__kg_per_m3, T_env__K, ao_mass__kg);
aero.model      = vat.gsi_models.Sentman(1, alpha_e);

%% ---- Geometry ----
fp.current_folder = fileparts(mfilename('fullpath'));
fp.obj_file        = fullfile(fp.current_folder, ...
    "geometries/shuttlecock_15360.obj");
% fp.obj_file      = fullfile(fp.current_folder, ...
%     "geometries/shuttlecock_61440.obj");

geometry = vat.geometry.RotatableMeshGeometry(fp.obj_file);

% Uncomment once to confirm which mesh_id belongs to which panel — VAT
% mesh IDs are 0-based (assimp load order), so the numbering below is
% only correct if the shuttlecock body itself occupies mesh 0.
% vat.visualization.show_meshes(geometry);

% Rotatable fins: mesh_id, hinge origin, hinge axis.
wings.up     = struct('mesh_id', 4, 'origin', [-0.15 -0.10 -0.05], ...
    'axis', [0 -1  0]);
wings.bottom = struct('mesh_id', 1, 'origin', [-0.15  0.10  0.05], ...
    'axis', [0  1  0]);
wings.left   = struct('mesh_id', 2, 'origin', [-0.15 -0.05  0.10], ...
    'axis', [0  0  1]);
wings.right  = struct('mesh_id', 3, 'origin', [-0.15  0.05 -0.10], ...
    'axis', [0  0 -1]);

%% ---- Shading / load pipeline ----
pipeline   = vat.shading.ShadingPipeline(geometry, 0, num_pixel);
calculator = vat.loads.HybridForceTorqueCalculator( ...
    geometry, pipeline, aero.model);

%% ---- Relative flow vector ----
% Standard wind-axes convention with alpha and beta
v_rel_fun = @(a, b, v) v .* [cos(a)*cos(b), sin(b), sin(a)*cos(b)];
v_rel__m_per_s = v_rel_fun(alpha__rad, beta__rad, 7800);

%% ---- Torque function handle for allocation / optimization ----
% torque function handle: 
% eta1: up/bottom fins
% eta2: left/right fins
torque_fun = @(eta) compute_torque(v_rel__m_per_s, geometry, ...
    aero.conditions, calculator, wings, surface_temp__K, eta(1), eta(2));

% torque_fun(deg2rad([90, -45]));


%% Nonlinear gradient free optimization

% Scalar objective function
tau_des = 1e-5.*[0;0;0]
f = @(eta) (sum((tau_des-torque_fun(eta)).^2));
x0 = [0;0];
lb = [-eta_max, -eta_max];
ub = [ eta_max,  eta_max];

opts = optimoptions('patternsearch', 'Display', 'iter', ...
    'PollMethod', 'MADSPositiveBasis2N');

% Call optimization
[x, fval, exitflag, output] = patternsearch(f, x0, [], [], [], [], ...
    lb, ub, [], opts);

% Show result
vat.visualization.show_meshes(geometry)

%% ================= Helper functions =================
function torque__Nm = compute_torque(v_rel__m_per_s, geometry, ...
    aero_conditions, calculator, wings, surface_temp__K, eta1, eta2)
% Rotate the fins to the commanded deflections, then evaluate the
% resulting aerodynamic torque about the flow direction v_rel__m_per_s.
% calc_aero_load returns [force, torque] (force first) — only the
% second output is the torque.

    set_panels(geometry, wings, eta1, eta2);
    [~, torque__Nm] = calculator.calc_aero_load( ...
        v_rel__m_per_s, surface_temp__K, aero_conditions);
    torque__Nm = torque__Nm(:);  % column vector, convenient for optimizers
end

function set_panels(geometry, wings, eta1__rad, eta2__rad)
% A positive eta deflects one panel of a pair, a negative eta its
% opposite. turn_mesh_around_axis is absolute, so every panel is
% commanded on every call and no state carries over between samples.
    turn(geometry, wings.up,     max( eta1__rad, 0));
    turn(geometry, wings.bottom, max(-eta1__rad, 0));
    turn(geometry, wings.left,   max( eta2__rad, 0));
    turn(geometry, wings.right,  max(-eta2__rad, 0));
    % vat.visualization.show_meshes(geometry)
end

function turn(geometry, wing, angle__rad)
    geometry.turn_mesh_around_axis( ...
        wing.mesh_id, angle__rad, wing.origin, wing.axis);
end